[package]
name = "nrf52L15-dk"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embassy-nrf = { version = "0.3.1", features = ["nrf54l15-app-s"] }
