[package]
name = "nrf52L15-dk"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
nrf-pac = { version = "0.1.0", features = ["nrf54l15-app"] }
rtt-target = "0.6.1"
